---
services:
  movies:
    image: adarshsengar/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: adarshsengar/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: adarshsengar/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: adarshsengar/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
